name: Clean Dump SAPA
# This process is manuel execution
on: [workflow_dispatch]
jobs:
  environement_Jena:
    runs-on: ubuntu-latest
    steps:
      # Open file with format lfs
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      
      - name: Download Apache Jena
        run: |
          download_url="https://dlcdn.apache.org/jena/binaries/apache-jena-5.4.0.zip"
          wget -O $RUNNER_TEMP/apache-jena-5.4.0.zip $download_url
          
      # unzip dump file
      - name: Unzip dump.ttl.gz file
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl

      # Jena Process
      - name: Install Apache Jena 5.4.0
        run: |
          sudo apt-get install unzip
          unzip $RUNNER_TEMP/apache-jena-5.4.0.zip -d apache-jena

      # chmod +x ${GITHUB_WORKSPACE}/apache-jena/apache-jena-5.4.0/
      - name: Add environement Apache Jena in Github Action
        run: |          
          export JENA_HOME=apache-jena/apache-jena-5.4.0/ >> "$GITHUB_PATH"
          export PATH=$JENA_HOME/bin >> "$GITHUB_PATH"
        
      - name: Execute Shell Clean Dump
        run: |
          chmod +x ${GITHUB_WORKSPACE}/generate-public-dmp.sh
          sh ${GITHUB_WORKSPACE}/generate-public-dmp.sh

      # JAs2701/test_dump
      - name: Checkout profile repo
        uses: actions/checkout@v4
        with:
          repository: JAs2701/test_dump
          path: public
          lfs: true
          #token: ${{ secrets.WEBSITE_UPDATE }}
      
      - name: Commit and push changes (if any)
        shell: bash
        env:
           CI_COMMIT_MESSAGE: update profile readme with latest posts
           CI_COMMIT_AUTHOR: github-actions[bot]
           CI_COMMIT_EMAIL: "jorge.aquino.jaq@gmail.com"
        run: |
            cd public
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
            if [[ `git status --porcelain --untracked-files=no` ]]; then
              # Changes
              git add README.md
              git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
              git lfs track "public-dump.ttl"
              git add public-dump.ttl
              git push
            else
              # No changes
              echo "no changes to latest posts"
              exit 0
            fi

      
      # Commit dump file clean
      #- name: Commit in Repository
      #  run: |
      #     git config user.name ${{ github.actor }}
      #     git config user.email "jorge.aquino.jaq@gmail.com"
      #     git lfs track "public-dump.ttl"
      #     git add ${GITHUB_WORKSPACE}/public-dump.ttl
      #     git commit -am "Commit public-dump.ttl"
      #     git push
