name: Clean Dump SAPA
# This process is manuel execution
on: [workflow_dispatch]
jobs:
  environement_Jena:
    runs-on: ubuntu-latest
    steps:
      # Open file with format lfs
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true
      
      - name: Download Apache Jena
        run: |
          download_url="https://dlcdn.apache.org/jena/binaries/apache-jena-5.4.0.zip"
          wget -O $RUNNER_TEMP/apache-jena-5.4.0.zip $download_url
      - name: Unzip package && Configuration environement Apache Jena
        run: |
          sudo apt-get install unzip
          unzip $RUNNER_TEMP/apache-jena-5.4.0.zip -d $RUNNER_TEMP/apache-jena
          # Add in environement Path
          echo "$RUNNER_TEMP/apache-jena/apache-jena-5.4.0/bin/" >> "$GITHUB_PATH"
      
      # unzip dump file
      - name: Extract dump.ttl.gz file
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl

      - run: |
          export JAVA_TOOL_OPTIONS=-Xmx1424m
          java -XX:+PrintFlagsFinal -version | grep HeapSize
      
      - name: Sparql Queries
        run: |
          chmod +x ${GITHUB_WORKSPACE}/generate-public-dmp.sh
          sh ${GITHUB_WORKSPACE}/generate-public-dmp.sh
