name: Apache Jena Update
# This process is manuel execution
on: [workflow_dispatch]
jobs:
  environement_Jena:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          check-latest: true

      - run: |
          java --version

      - name: Download Apache Jena
        run: |
          download_url="https://dlcdn.apache.org/jena/binaries/apache-jena-5.4.0.zip"
          wget -O $RUNNER_TEMP/apache-jena-5.4.0.zip $download_url
      - name: Unzip package && Configuration environement Apache Jena
        run: |
          sudo apt-get install unzip
          unzip $RUNNER_TEMP/apache-jena-5.4.0.zip -d $RUNNER_TEMP/apache-jena

          echo "$RUNNER_TEMP/apache-jena/apache-jena-5.4.0/bin/" >> "$GITHUB_PATH"

          
      - run: |          
          update --version
