name: Apache Jena Update
# This process is manuel execution
on: [workflow_dispatch]
jobs:
  environement_Jena:
    runs-on: ubuntu-latest
    steps:
      - name: Download Java
        run: |
          download_url="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.10%2B9/OpenJDK11U-jdk_x64_linux_hotspot_11.0.10_9.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '17'
          architecture: x64
