name: Clean Dumps
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      # unzip dump file
      - uses: actions/checkout@v4
      - name: Extract dump.ttl.gz file
        id: dump
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl
      
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # Jena4 requires Java 11+
      - uses: foooomio/setup-jena@v3
      - run: update --data dump.ttl --update ./sparql/all.ru --dump >> public-dump.ttl

      #- run: |
      #    pwd dump.ttl
      #    ls dump.ttl
      #    chmod +x ${GITHUB_WORKSPACE}/generate-public-dmp.sh
      #    sh ${GITHUB_WORKSPACE}/generate-public-dmp.sh
      
      - name: Save in Repository
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "jorge.aquino.jaq@gmail.com"
          git lfs track "public-dump.ttl"
          git add ${GITHUB_WORKSPACE}/public-dump.ttl
          git commit -am "Save dum.ttl in repository"
          git push
