name: Clean Dumps
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      # unzip dump file
      - uses: actions/checkout@v4
      - name: Extract dump.ttl.gz file
        id: dump
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl

      - name: Print all directory in repository
        run: |
          ls -la
          ls -la ${{ runner.temp }}
          
  Sparql_Dump:
    runs-on: ubuntu-latest
    needs: [dump]
    steps:
      - run: chmod +x ${GITHUB_WORKSPACE}/generate-public-dump.sh          
    
      # Install Apache Jena
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # Jena4 requires Java 11+
      - uses: foooomio/setup-jena@latest
      - run: sh ${GITHUB_WORKSPACE}/generate-public-dump.sh
      
      # Execute Update in sparql
      #- uses: actions/checkout@v4
      #- name: Run the script
      #  run: |
          

      - name: Save in Repository
        run: |
          git config user.name ${{ github.actor }}
          git config user.email "jorge.aquino.jaq@gmail.com"
          git lfs track "public-dump.ttl"
          git add ${GITHUB_WORKSPACE}/public-dump.ttl
          git commit -am "Save dum.ttl in repository"
          git push
