name: Clean Dumps
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Unzip file
        uses: ihiroky/extract-action@v1
        with:
          file_path: dump.ttl.gz
          extract_dir: dump/dump.ttl


  Jena:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # Jena4 requires Java 11+
      - uses: foooomio/setup-jena@v3
      - run: update --version
