name: Clean Dumps
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Create Directory
      - name: create directory
        run: |
          mkdir dump
      # unzip
      - uses: actions/checkout@v3
      - name: Extract dump.ttl.gz
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl

  Jena:
    runs-on: ubuntu-latest
    needs: [dump]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # Jena4 requires Java 11+
      - uses: foooomio/setup-jena@v3
      - run: update --version
