name: Clean Dumps
on: [workflow_dispatch]
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      # unzip
      - uses: actions/checkout@v4
      - name: Extract dump.ttl.gz file
        id: dump
        run: |
          gunzip -fdc dump.ttl.gz > dump.ttl

  print:
    runs-on: ubuntu-latest
    needs: [dump]
    steps:
      - name: print
        run: 
          pwd dump.ttl
          echo dump.ttl

  Jena:
    runs-on: ubuntu-latest
    needs: [dump]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17 # Jena4 requires Java 11+
      - uses: foooomio/setup-jena@v3
      - run: update --version

      - name: Make the script files executable
        run: chmod +x my-script.sh my-other-script.sh
      - name: Run the script
        run: ./generate-public-dump.sh
